rabbitmq:
  image: rabbitmq:3
  net: host
  hostname: rabbitmq

neutron:
  extends:
    file: $BASE/neutron.yml
    service: neutron
  image: sandbox/neutron:liberty
  command: ['/run-neutron-rabbit.sh']
  hostname: neutron
  links:
  - "keystone:keystone"
  - "cluster:midonetapi"

lbaasagent:
  image: sandbox/neutron-lbaas:liberty
  hostname: neutron-lbaas
  net: host
  privileged: true
  volumes_from:
  - midolman

midolman:
  extends:
    file: $BASE/midolman.yml
    service: midolman
  image: sandbox/midolman:master
  net: host
  volumes:
  - /var/log/sandbox/midolman:/var/log/midolman
  - /etc/sandbox
  - /var/run/midolman
  command: ['/run-midolman-host.sh']
  volumes_from:
  - zookeeper1

zookeeper1:
  extends:
    file: $BASE/zookeeper.yml
    service: zookeeper
  image: sandbox/zookeeper:3.4.5
  hostname: zookeeper1
  volumes:
  - /zoo/conf/
  - /var/log/sandbox/zookeeper/1:/var/log/zookeeper
  environment:
  - ZOO_ID=1

zookeeper2:
  extends:
    file: $BASE/zookeeper.yml
    service: zookeeper
  image: sandbox/zookeeper:3.4.5
  hostname: zookeeper2
  environment:
  - ZOO_ID=2
  volumes:
  - /var/log/sandbox/zookeeper/2:/var/log/zookeeper
  volumes_from:
  - zookeeper1

zookeeper3:
  extends:
    file: $BASE/zookeeper.yml
    service: zookeeper
  image: sandbox/zookeeper:3.4.5
  hostname: zookeeper3
  environment:
  - ZOO_ID=3
  volumes:
  - /var/log/sandbox/zookeeper/3:/var/log/zookeeper
  volumes_from:
  - zookeeper1
  links:
  - zookeeper1:zk1
  - zookeeper2:zk2

cluster:
  extends:
    file: $BASE/midonet-cluster.yml
    service: cluster
  image: sandbox/midonet-cluster:master
  hostname: cluster
  links:
  - "zookeeper1:zk1"
  - "zookeeper2:zk2"
  - "zookeeper3:zk3"
  - "keystone:keystone"
  volumes:
  - /var/log/sandbox/midonet-cluster:/var/log/midonet-cluster

keystone:
  extends:
    file: $BASE/keystone.yml
    service: keystone
  image: sandbox/keystone:liberty
  hostname: keystone
  volumes:
  - /var/log/sandbox/keystone:/var/log/keystone
